### PR TITLE
fix(TD-14113): fix stmt memory leak in case of exception

### LINKED ISSUE #17: Exception safety issue in `stmt.rs`
In function `bind`, all the `BindParam` are freed by `BindParam::free()`:

https://github.com/taosdata/libtaos-rs/blob/a8a46cf5a0589aaf3881f942def43484ba861aaa/src/stmt.rs#L66

However, there is a potential memory leak because errors may happen, thus `bind` returns before calling `free`.

https://github.com/taosdata/libtaos-rs/blob/a8a46cf5a0589aaf3881f942def43484ba861aaa/src/stmt.rs#L61-L63

Probably `free` should be implemented as an automatic destructor through the `Drop` trait so that Rust can automatically deallocate memory.

### PR DESCRIPTION
**Pull request by zitsen**
close #17

### CODE REVIEW

**Comment by zitsen** [comment]
Appreciate your review if possible, @lizhuohua.

**Comment by lizhuohua** [comment]
Looks good to me. Many thanks!

**Review by zhaoyanggh — APPROVED** [review]
LGTM

**Review by sangshuduo — APPROVED** [review]
LGTM

**Pull request merged**
